repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
        files: \.py$
    -   id: pretty-format-json
    -   id: trailing-whitespace
        files: \.py$
-   repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
    -   id: black
        language_version: python3
        args: [--line-length=79]
