version: "3"

services:
  app:
    build:
      context: .
      args:
        DJANGO_REQUIREMENTS: development
    volumes:
      - .:/srv/app/
    env_file:
      - settings/.settings-development.env
    environment:
      - APP_VERSION=latest
      - ENVIRONMENT=development
      - DJANGO_SETTINGS_MODULE=settings.development
    ports:
      - "8000:8000"

  database:
    build:
      context: docker/postgres
    ports:
      - $MAVEDB_DB_PORT:5432
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./docker/postgres/dumps:/home/dumps:ro
    environment:
      POSTGRES_USER: $MAVEDB_DB_USER
      POSTGRES_PASSWORD: $MAVEDB_DB_PASSWORD
      POSTGRES_DB: $MAVEDB_DB_NAME
      MAVEDB_DUMP_FILE: "mavedb_2020_07_28.dump"

  broker:
    image: rabbitmq:3.8.3
    ports:
      - $MAVEDB_BROKER_PORT:5672

volumes:
  database-data:
