version: "3"

services:
  app:
    image: mavedb/mavedb:${MAVEDB_RELEASE_TAG}
    volumes:
      - celery-logs:/var/log/celery/
      - app-logs:/srv/app/logs/
      - static-files:/srv/app/static
    env_file:
      - settings/.settings-production.env
    environment:
      - APP_VERSION=$MAVEDB_RELEASE_TAG
      - ENVIRONMENT=production
      - DJANGO_SETTINGS_MODULE=settings.production

  database:
    build:
      context: docker/postgres
    ports:
      - $MAVEDB_DB_PORT:5432
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./docker/postgres/dumps:/home/dumps:ro
    environment:
      POSTGRES_USER: $MAVEDB_DB_USER
      POSTGRES_PASSWORD: $MAVEDB_DB_PASSWORD
      POSTGRES_DB: $MAVEDB_DB_NAME
      MAVEDB_DUMP_FILE: "mavedb_2020_07_28.dump"

  broker:
    image: rabbitmq:3.8.3
    ports:
      - $MAVEDB_BROKER_PORT:5672

  server:
    build:
      context: docker/nginx
    ports:
      - 8001:80
      - 8002:443
    volumes:
      - static-files:/srv/app/static/
      - server-logs:/var/log/nginx/

volumes:
  celery-logs:
  app-logs:
  static-files:
  server-logs:
  database-data:
