# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 08:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import scoreset.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiment', '0004_auto_20170802_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(default=None, max_length=64, unique=True, validators=[scoreset.validators.valid_scs_accession], verbose_name='Accession')),
                ('creation_date', models.DateField(default=datetime.date.today, verbose_name='Creation date')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('private', models.BooleanField(default=True, verbose_name='Private')),
                ('abstract', models.TextField(blank=True, default='', verbose_name='Abstract')),
                ('method_desc', models.TextField(blank=True, default='', verbose_name='Method description')),
                ('sra_id', models.TextField(blank=True, default='', verbose_name='SRA identifier')),
                ('doi_id', models.TextField(blank=True, default='', verbose_name='DOI identifier')),
                ('experiment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='experiment.Experiment')),
            ],
            options={
                'verbose_name': 'Experiment',
                'verbose_name_plural': 'Experiments',
                'ordering': ['-creation_date'],
            },
        ),
    ]
