# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-15 04:23
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoreset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreset',
            name='last_edit_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Last edited on'),
        ),
        migrations.AddField(
            model_name='scoreset',
            name='publish_date',
            field=models.DateField(default=None, null=True, verbose_name='Published on'),
        ),
        migrations.AddField(
            model_name='variant',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='scoreset',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Created on'),
        ),
    ]
