# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 05:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreset',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='Metadata'),
        ),
    ]
