# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170808_1348'),
        ('scoreset', '0002_scoreset_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreset',
            name='keywords',
            field=models.ManyToManyField(to='main.Keyword'),
        ),
    ]
