# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 08:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scoreset', '0003_auto_20170816_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scs_created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='scoreset',
            name='last_edit_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='scs_edited_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Last edited by'),
        ),
    ]
