# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 04:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import scoreset.validators


class Migration(migrations.Migration):

    dependencies = [
        ('scoreset', '0005_auto_20170810_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'counts': {'count': [None], 'hgvs': [None]}, 'scores': {'hgvs': [None], 'score': [None], 'se': [None]}}, validators=[scoreset.validators.valid_variant_json], verbose_name='Data columns'),
        ),
    ]
