# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreset', '0006_auto_20170825_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreset',
            name='replaced_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scoreset.ScoreSet'),
        ),
    ]
