# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 04:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import scoreset.validators


class Migration(migrations.Migration):

    dependencies = [
        ('scoreset', '0006_auto_20170810_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreset',
            name='dataset_columns',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'counts': ['hgvs', 'count'], 'scores': ['hgvs', 'score', 'se']}, validators=[scoreset.validators.valid_scoreset_json], verbose_name='Dataset columns'),
        ),
    ]
