# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-03 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreset', '0007_scoreset_replaced_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreset',
            name='replaced_by',
        ),
        migrations.AddField(
            model_name='scoreset',
            name='replaces',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='replaced_by', to='scoreset.ScoreSet', verbose_name='Replaces'),
        ),
    ]
