# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreset', '0007_auto_20170810_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='hgvs_string',
            new_name='hgvs',
        ),
    ]
