# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-11 04:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import scoreset.validators


class Migration(migrations.Migration):

    dependencies = [
        ('scoreset', '0008_auto_20170810_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreset',
            name='dataset_columns',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'counts': ['hgvs'], 'scores': ['hgvs']}, validators=[scoreset.validators.valid_scoreset_json], verbose_name='Dataset columns'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'counts': {'hgvs': None}, 'scores': {'hgvs': None}}, validators=[scoreset.validators.valid_variant_json], verbose_name='Data columns'),
        ),
    ]
