# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170919_1705'),
        ('scoreset', '0011_auto_20170914_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreset',
            name='licence_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attached_scoresets', to='main.Licence', verbose_name='Licence'),
        ),
    ]
