# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoreset', '0012_scoreset_licence_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreset',
            name='licence_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attached_scoresets', to='main.Licence', verbose_name='Licence'),
        ),
    ]
