# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-19 06:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_auto_20181001_1906"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="submission_errors",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=None, null=True
            ),
        ),
    ]
