# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-01 04:20
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import variant.validators


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'count_data': {}, 'score_data': {}}, validators=[variant.validators.validate_variant_json], verbose_name='Data columns'),
        ),
    ]
