# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-18 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("variant", "0003_auto_20180618_1643")]

    operations = [
        migrations.RenameField(
            model_name="variant", old_name="hgvs_p", new_name="hgvs_pro"
        )
    ]
