# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-29 05:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import variant.models
import variant.validators


class Migration(migrations.Migration):

    dependencies = [("variant", "0004_auto_20180618_1712")]

    operations = [
        migrations.AlterField(
            model_name="variant",
            name="data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=variant.models.default_data_dict,
                validators=[variant.validators.validate_variant_json],
                verbose_name="Data columns",
            ),
        )
    ]
