# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-06 05:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoiIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('identifier', models.CharField(default=None, max_length=256, unique=True, verbose_name='Identifier')),
                ('dbname', models.CharField(default=None, max_length=256, verbose_name='Database name')),
                ('url', models.URLField(blank=True, default=None, max_length=256, null=True, verbose_name='Identifier URL')),
            ],
            options={
                'verbose_name': 'DOI',
                'verbose_name_plural': 'DOIs',
            },
        ),
        migrations.CreateModel(
            name='EnsemblIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('identifier', models.CharField(default=None, max_length=256, unique=True, verbose_name='Identifier')),
                ('dbname', models.CharField(default=None, max_length=256, verbose_name='Database name')),
                ('url', models.URLField(blank=True, default=None, max_length=256, null=True, verbose_name='Identifier URL')),
            ],
            options={
                'verbose_name': 'Ensembl accession',
                'verbose_name_plural': 'Ensembl accessions',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('text', models.CharField(default=None, max_length=256, unique=True, verbose_name='Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='PubmedIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('identifier', models.CharField(default=None, max_length=256, unique=True, verbose_name='Identifier')),
                ('dbname', models.CharField(default=None, max_length=256, verbose_name='Database name')),
                ('url', models.URLField(blank=True, default=None, max_length=256, null=True, verbose_name='Identifier URL')),
                ('reference_html', models.TextField(blank=True, default=None, null=True, verbose_name='Formatted reference')),
            ],
            options={
                'verbose_name': 'PubMed identifier',
                'verbose_name_plural': 'PubMed identifiers',
            },
        ),
        migrations.CreateModel(
            name='RefseqIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('identifier', models.CharField(default=None, max_length=256, unique=True, verbose_name='Identifier')),
                ('dbname', models.CharField(default=None, max_length=256, verbose_name='Database name')),
                ('url', models.URLField(blank=True, default=None, max_length=256, null=True, verbose_name='Identifier URL')),
            ],
            options={
                'verbose_name': 'RefSeq accession',
                'verbose_name_plural': 'RefSeq accessions',
            },
        ),
        migrations.CreateModel(
            name='SraIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('identifier', models.CharField(default=None, max_length=256, unique=True, verbose_name='Identifier')),
                ('dbname', models.CharField(default=None, max_length=256, verbose_name='Database name')),
                ('url', models.URLField(blank=True, default=None, max_length=256, null=True, verbose_name='Identifier URL')),
            ],
            options={
                'verbose_name': 'SRA accession',
                'verbose_name_plural': 'SRA accessions',
            },
        ),
        migrations.CreateModel(
            name='UniprotIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('identifier', models.CharField(default=None, max_length=256, unique=True, verbose_name='Identifier')),
                ('dbname', models.CharField(default=None, max_length=256, verbose_name='Database name')),
                ('url', models.URLField(blank=True, default=None, max_length=256, null=True, verbose_name='Identifier URL')),
            ],
            options={
                'verbose_name': 'UniProt accession',
                'verbose_name_plural': 'UniProt accessions',
            },
        ),
    ]
