# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-18 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0002_auto_20180418_1820'),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensembloffset',
            name='offset',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Wild-type offset'),
        ),
        migrations.AddField(
            model_name='ensembloffset',
            name='target',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ensembloffset', to='genome.TargetGene', verbose_name='Target gene'),
        ),
        migrations.AddField(
            model_name='refseqoffset',
            name='offset',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Wild-type offset'),
        ),
        migrations.AddField(
            model_name='refseqoffset',
            name='target',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='refseqoffset', to='genome.TargetGene', verbose_name='Target gene'),
        ),
        migrations.AddField(
            model_name='uniprotoffset',
            name='offset',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Wild-type offset'),
        ),
        migrations.AddField(
            model_name='uniprotoffset',
            name='target',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='uniprotoffset', to='genome.TargetGene', verbose_name='Target gene'),
        ),
    ]
