# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-17 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20180411_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensemblidentifier',
            name='offset',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Wild-type offset'),
        ),
        migrations.AddField(
            model_name='refseqidentifier',
            name='offset',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Wild-type offset'),
        ),
        migrations.AddField(
            model_name='uniprotidentifier',
            name='offset',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Wild-type offset'),
        ),
    ]
