# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-23 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import metadata.validators


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20180418_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensembloffset',
            name='identifier',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='offset', to='metadata.EnsemblIdentifier', validators=[metadata.validators.validate_ensembl_identifier], verbose_name='Ensembl identifier'),
        ),
        migrations.AlterField(
            model_name='refseqoffset',
            name='identifier',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='offset', to='metadata.RefseqIdentifier', validators=[metadata.validators.validate_refseq_identifier], verbose_name='RefSeq identifier'),
        ),
        migrations.AlterField(
            model_name='uniprotoffset',
            name='identifier',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='offset', to='metadata.UniprotIdentifier', validators=[metadata.validators.validate_uniprot_identifier], verbose_name='UniProt identifier'),
        ),
    ]
