# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-25 04:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_auto_20180423_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doiidentifier',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 25, 14, 28, 19, 31529), verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='doiidentifier',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='ensemblidentifier',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 25, 14, 28, 19, 31529), verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='ensemblidentifier',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='pubmedidentifier',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 25, 14, 28, 19, 31529), verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='pubmedidentifier',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='refseqidentifier',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 25, 14, 28, 19, 31529), verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='refseqidentifier',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='sraidentifier',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 25, 14, 28, 19, 31529), verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='sraidentifier',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification date'),
        ),
        migrations.AlterField(
            model_name='uniprotidentifier',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 25, 14, 28, 19, 31529), verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='uniprotidentifier',
            name='modification_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification date'),
        ),
    ]
