# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-29 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("metadata", "0003_auto_20190208_1539")]

    operations = [
        migrations.AlterModelOptions(
            name="pubmedidentifier",
            options={
                "ordering": ("reference_html",),
                "verbose_name": "PubMed identifier",
                "verbose_name_plural": "PubMed identifiers",
            },
        )
    ]
