# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-17 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_auto_20180417_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationOffset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.PositiveIntegerField(blank=True, default=1, verbose_name='Wild-type offset')),
            ],
        ),
        migrations.RemoveField(
            model_name='ensemblidentifier',
            name='offset',
        ),
        migrations.RemoveField(
            model_name='refseqidentifier',
            name='offset',
        ),
        migrations.RemoveField(
            model_name='uniprotidentifier',
            name='offset',
        ),
        migrations.AddField(
            model_name='ensemblidentifier',
            name='annotation_offset',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.AnnotationOffset', verbose_name='Wild-type offset'),
        ),
        migrations.AddField(
            model_name='refseqidentifier',
            name='annotation_offset',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.AnnotationOffset', verbose_name='Wild-type offset'),
        ),
        migrations.AddField(
            model_name='uniprotidentifier',
            name='annotation_offset',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='metadata.AnnotationOffset', verbose_name='Wild-type offset'),
        ),
    ]
