# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-29 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("metadata", "0004_auto_20190729_1501")]

    operations = [
        migrations.AlterModelOptions(
            name="pubmedidentifier",
            options={
                "ordering": ("id",),
                "verbose_name": "PubMed identifier",
                "verbose_name_plural": "PubMed identifiers",
            },
        )
    ]
