# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-25 04:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_auto_20180425_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doiidentifier',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='ensemblidentifier',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='pubmedidentifier',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='refseqidentifier',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='sraidentifier',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='uniprotidentifier',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Creation date'),
        ),
    ]
