# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-08-25 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("metadata", "0006_auto_20190729_1510"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pubmedidentifier",
            options={
                "ordering": ("reference_html",),
                "verbose_name": "PubMed ID",
                "verbose_name_plural": "PubMed IDs",
            },
        ),
        migrations.AlterModelOptions(
            name="sraidentifier",
            options={
                "verbose_name": "Raw reads accession",
                "verbose_name_plural": "Raw reads accessions",
            },
        ),
    ]
