# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 02:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
