# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 05:30
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='documentation',
            field=markdownx.models.MarkdownxField(default=''),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='privacy',
            field=markdownx.models.MarkdownxField(default=''),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='terms',
            field=markdownx.models.MarkdownxField(default=''),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='usage_guide',
            field=markdownx.models.MarkdownxField(default=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=markdownx.models.MarkdownxField(default=''),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='about',
            field=markdownx.models.MarkdownxField(default=''),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='citation',
            field=markdownx.models.MarkdownxField(default=''),
        ),
    ]
