# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-20 06:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinformation',
            old_name='_about',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='siteinformation',
            old_name='_citation',
            new_name='citation',
        ),
        migrations.RenameField(
            model_name='siteinformation',
            old_name='_documentation',
            new_name='documentation',
        ),
        migrations.RenameField(
            model_name='siteinformation',
            old_name='_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='siteinformation',
            old_name='_privacy',
            new_name='privacy',
        ),
        migrations.RenameField(
            model_name='siteinformation',
            old_name='_terms',
            new_name='terms',
        ),
        migrations.RenameField(
            model_name='siteinformation',
            old_name='_usage_guide',
            new_name='usage_guide',
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='version',
            field=models.CharField(default='1', max_length=256),
        ),
        migrations.AddField(
            model_name='siteinformation',
            name='version_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
