# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 05:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiment', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAccession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('name', models.TextField(default=None)),
            ],
            options={
                'verbose_name': 'Other accession',
                'verbose_name_plural': 'other accessions',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None)),
                ('creation_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('reference', models.TextField(default=None, verbose_name='Reference')),
                ('is_alternate', models.BooleanField(default=False, verbose_name='Alternate reference')),
                ('target_start', models.PositiveIntegerField(default=None, verbose_name='Target start')),
                ('target_end', models.PositiveIntegerField(default=None, verbose_name='Target end')),
                ('ref_start', models.PositiveIntegerField(default=None, verbose_name='Reference start')),
                ('ref_end', models.PositiveIntegerField(default=None, verbose_name='Reference end')),
                ('experiment', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='experiment.Experiment')),
            ],
            options={
                'verbose_name': 'Reference mapping',
                'verbose_name_plural': 'Reference mappings',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='TargetOrganism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('name', models.TextField(default=None)),
            ],
            options={
                'verbose_name': 'Target organism',
                'verbose_name_plural': 'Target organisms',
                'ordering': ['-creation_date'],
            },
        ),
    ]
