# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-12 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalaccession',
            name='text',
            field=models.CharField(default=None, max_length=256, unique=True, verbose_name='Accession'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='text',
            field=models.CharField(default=None, max_length=256, unique=True, verbose_name='Keyword'),
        ),
    ]
