# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-10 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180510_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='branch',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='version',
            field=models.CharField(default='', max_length=250),
        ),
    ]
