# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170710_1257'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='news',
            order_with_respect_to='date',
        ),
    ]
