# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-02 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='level',
            field=models.CharField(blank=True, choices=[('Happy holidays', 'Happy holidays'), ('April fools', 'April fools'), ('Information', 'Information'), ('Important', 'Important'), ('Critical', 'Critical')], default='Information', max_length=250),
        ),
    ]
