# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiment', '0001_initial'),
        ('scoreset', '0002_scoreset_metadata'),
        ('main', '0002_externalaccession_keyword_referencemapping_targetorganism'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='experiment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='experiment.Experiment'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='scoreset',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='scoreset.ScoreSet'),
        ),
    ]
