# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-16 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180510_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='citation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='documentation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='privacy',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='terms',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='usage_guide',
            field=models.TextField(default=''),
        ),
    ]
