# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 03:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170710_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='news',
            order_with_respect_to=None,
        ),
    ]
