# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170814_1449'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={},
        ),
    ]
