# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170727_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinformation',
            old_name='about',
            new_name='_about',
        ),
        migrations.RenameField(
            model_name='siteinformation',
            old_name='citation',
            new_name='_citation',
        ),
        migrations.RenameField(
            model_name='siteinformation',
            old_name='documentation',
            new_name='_documentation',
        ),
        migrations.RenameField(
            model_name='siteinformation',
            old_name='privacy',
            new_name='_privacy',
        ),
        migrations.RenameField(
            model_name='siteinformation',
            old_name='terms',
            new_name='_terms',
        ),
        migrations.RenameField(
            model_name='siteinformation',
            old_name='usage_guide',
            new_name='_usage_guide',
        ),
    ]
