# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170727_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(default='default news.'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='_about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='_citation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='_documentation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='_privacy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='_terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='_usage_guide',
            field=models.TextField(blank=True, default=''),
        ),
    ]
