# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170824_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
