# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170710_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(default='')),
                ('citation', models.TextField(default='')),
            ],
        ),
    ]
