# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170808_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalaccession',
            old_name='name',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='name',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='targetorganism',
            old_name='name',
            new_name='text',
        ),
    ]
