# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_siteinformation__email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(default=None, max_length=2048, verbose_name='Long name')),
                ('short_name', models.CharField(default=None, max_length=2048, verbose_name='Short name')),
                ('text', models.TextField(default=None, verbose_name='Licence')),
                ('link', models.FloatField(default=None, verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Licence',
                'verbose_name_plural': 'Licence',
            },
        ),
    ]
