# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_siteinformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': 'News item', 'verbose_name_plural': 'News items'},
        ),
        migrations.AlterModelOptions(
            name='siteinformation',
            options={'verbose_name': 'Site Information', 'verbose_name_plural': 'Site Information'},
        ),
    ]
