# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170808_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalaccession',
            name='text',
            field=models.TextField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='text',
            field=models.TextField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='targetorganism',
            name='text',
            field=models.TextField(default=None, unique=True),
        ),
    ]
