# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170721_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreset',
            name='doi',
            field=models.TextField(default='Not provided', verbose_name='DOI'),
        ),
    ]
