# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-30 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0006_auto_20190730_1733")]

    operations = [
        migrations.AlterField(
            model_name="licence",
            name="long_name",
            field=models.CharField(
                default=None, max_length=200, verbose_name="Long name"
            ),
        )
    ]
