# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='version',
            field=models.FloatField(default=None, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='licence',
            name='link',
            field=models.CharField(default=None, max_length=2048, verbose_name='Link'),
        ),
    ]
