# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_referencemapping_experiment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referencemapping',
            old_name='ref_end',
            new_name='reference_end',
        ),
        migrations.RenameField(
            model_name='referencemapping',
            old_name='ref_start',
            new_name='reference_start',
        ),
    ]
