# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170919_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licence',
            name='text',
        ),
        migrations.AddField(
            model_name='licence',
            name='legal_code',
            field=models.TextField(default=None, verbose_name='Legal Code'),
        ),
    ]
