# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_experiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='accession',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='alt_reference',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='author',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='keywords',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='reference',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='scoring_method',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='target',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
