# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 06:02
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170712_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='accession',
            field=models.CharField(default='', max_length=1024, verbose_name='Accession'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='alt_reference',
            field=models.CharField(default='', max_length=1024, verbose_name='Seconary reference'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='author',
            field=models.CharField(default='', max_length=1024, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='base_coverage',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Average base coverage'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Publication date'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='keywords',
            field=models.CharField(default='', max_length=1024, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='num_variants',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Variant count'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='read_depth',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Average read depth'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='reference',
            field=models.CharField(default='', max_length=1024, verbose_name='Primary reference'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='scoring_method',
            field=models.CharField(default='', max_length=1024, verbose_name='Scoring method'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='target',
            field=models.CharField(default='', max_length=1024, verbose_name='Target'),
        ),
    ]
