# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_experiment_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession', models.CharField(default='', max_length=1024, verbose_name='Accession')),
                ('description', models.TextField(default='')),
                ('theory', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='experiment',
            name='author',
            field=models.TextField(default='', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='keywords',
            field=models.TextField(default='', verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='scoring_method',
            field=models.TextField(default='', verbose_name='Scoring method'),
        ),
        migrations.AddField(
            model_name='scoreset',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Experiment'),
        ),
    ]
