# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 08:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20170718_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='base_coverage',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='read_depth',
        ),
    ]
