# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-18 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencemap',
            options={'verbose_name': 'Reference map', 'verbose_name_plural': 'Reference maps'},
        ),
    ]
