# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-11 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0002_auto_20180411_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='chromosome',
            field=models.CharField(default=None, max_length=32, verbose_name='Chromosome identifier'),
        ),
    ]
