# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-01 04:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0002_auto_20180429_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetgene',
            name='ensembl_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_targetgenes', to='metadata.EnsemblIdentifier'),
        ),
        migrations.AlterField(
            model_name='targetgene',
            name='refseq_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_targetgenes', to='metadata.RefseqIdentifier'),
        ),
        migrations.AlterField(
            model_name='targetgene',
            name='uniprot_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_targetgenes', to='metadata.UniprotIdentifier'),
        ),
    ]
