# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-18 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0002_auto_20180418_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencegenome',
            name='ensembl_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_referencegenomes', to='metadata.EnsemblIdentifier', verbose_name='Ensembl identifier'),
        ),
        migrations.AlterField(
            model_name='referencegenome',
            name='refseq_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_referencegenomes', to='metadata.RefseqIdentifier', verbose_name='RefSeq identifier'),
        ),
        migrations.AlterField(
            model_name='referencemap',
            name='genome',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='associated_reference_maps', to='genome.ReferenceGenome', verbose_name='Reference genome'),
        ),
        migrations.AlterField(
            model_name='targetgene',
            name='ensembl_id',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_targetgenes', to='metadata.EnsemblIdentifier'),
        ),
        migrations.AlterField(
            model_name='targetgene',
            name='refseq_id',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_targetgenes', to='metadata.RefseqIdentifier'),
        ),
        migrations.AlterField(
            model_name='targetgene',
            name='uniprot_id',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_targetgenes', to='metadata.UniprotIdentifier'),
        ),
    ]
