# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-20 06:43
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import genome.validators


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0003_auto_20180418_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenomicInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=datetime.date.today, verbose_name='Creation date')),
                ('modification_date', models.DateField(default=datetime.date.today, verbose_name='Modification date')),
                ('start', models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1, message='Start coordinate must be a positive integer.')], verbose_name='Start')),
                ('end', models.PositiveIntegerField(default=None, validators=[django.core.validators.MinValueValidator(1, message='End coordinate must be a positive integer.')], verbose_name='End (inclusive)')),
                ('chromosome', models.CharField(default=None, max_length=32, validators=[genome.validators.validate_chromosome], verbose_name='Chromosome identifier')),
                ('strand', models.CharField(choices=[('+', '+'), ('-', '-')], default=None, max_length=1, validators=[genome.validators.validate_strand], verbose_name='Strand')),
                ('reference_map', models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='genome.ReferenceMap')),
            ],
            options={
                'verbose_name': 'Reference interval',
                'verbose_name_plural': 'Reference intervals',
                'ordering': ['start'],
            },
        ),
        migrations.RemoveField(
            model_name='interval',
            name='reference_map',
        ),
        migrations.DeleteModel(
            name='Interval',
        ),
    ]
