# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0004_auto_20180412_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='intervals',
        ),
        migrations.RemoveField(
            model_name='targetgene',
            name='annotations',
        ),
        migrations.AddField(
            model_name='annotation',
            name='target',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='genome.TargetGene'),
        ),
        migrations.AddField(
            model_name='interval',
            name='annotation',
            field=models.ForeignKey(default=None, null=None, on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='genome.Annotation'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='genome',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='genome.ReferenceGenome', verbose_name='Annotation genome'),
        ),
        migrations.AlterField(
            model_name='referencegenome',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
