# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-04 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import genome.validators


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0004_auto_20180510_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referencegenome',
            old_name='species_name',
            new_name='organism_name',
        ),
    ]
