# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-13 06:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0006_auto_20180413_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='genome',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='genome.ReferenceGenome', verbose_name='Reference genome'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='target',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='genome.TargetGene', verbose_name='Target'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='annotation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='genome.Annotation'),
        ),
        migrations.AlterField(
            model_name='targetgene',
            name='wt_sequence',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='genome.WildTypeSequence', verbose_name='Wildtype Sequence'),
        ),
    ]
