# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("genome", "0007_auto_20181203_1303")]

    operations = [
        migrations.AlterModelOptions(
            name="referencegenome",
            options={
                "ordering": ("id",),
                "verbose_name": "Reference Genome",
                "verbose_name_plural": "Reference Genomes",
            },
        ),
        migrations.AlterModelOptions(
            name="targetgene",
            options={
                "ordering": ("name",),
                "verbose_name": "Target Gene",
                "verbose_name_plural": "Target Genes",
            },
        ),
    ]
