# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-27 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0007_genomeidentifier'),
        ('genome', '0007_auto_20180425_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencegenome',
            name='ensembl_id',
        ),
        migrations.RemoveField(
            model_name='referencegenome',
            name='refseq_id',
        ),
        migrations.AddField(
            model_name='referencegenome',
            name='genome_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_referencegenomes', to='metadata.GenomeIdentifier', verbose_name='Genome assembly identifier'),
        ),
    ]
