# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-13 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0007_auto_20180413_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencegenome',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='annotation',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
