# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-13 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0008_auto_20180413_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Primary'),
        ),
    ]
