# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-07 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0008_auto_20181203_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetgene',
            name='category',
            field=models.CharField(choices=[('Coding', 'Coding'), ('Non-coding', 'Non-coding'), ('Promoter', 'Promoter'), ('Enhancer', 'Enhancer')], default='Coding', max_length=250, verbose_name='Target category'),
        ),
    ]
