# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-08 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("genome", "0009_targetgene_category")]

    operations = [
        migrations.AlterModelOptions(
            name="referencegenome",
            options={
                "ordering": ("id",),
                "verbose_name": "Reference genome",
                "verbose_name_plural": "Reference genomes",
            },
        ),
        migrations.AlterField(
            model_name="targetgene",
            name="category",
            field=models.CharField(
                choices=[
                    ("Protein coding", "Protein coding"),
                    ("Regulatory", "Regulatory"),
                    ("Other noncoding", "Other noncoding"),
                ],
                default="Protein coding",
                max_length=250,
                verbose_name="Target type",
            ),
        ),
    ]
