# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-16 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import genome.validators


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0010_targetgene_scoreset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interval',
            options={'ordering': ['start'], 'verbose_name': 'Reference interval', 'verbose_name_plural': 'Reference intervals'},
        ),
        migrations.AlterModelOptions(
            name='wildtypesequence',
            options={'verbose_name': 'Wild-type sequence', 'verbose_name_plural': 'Wild-type sequences'},
        ),
        migrations.AlterField(
            model_name='referencegenome',
            name='ensembl_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_referencegenomes', to='metadata.EnsemblIdentifier', verbose_name='Ensembl identifier'),
        ),
        migrations.AlterField(
            model_name='referencegenome',
            name='refseq_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_referencegenomes', to='metadata.RefseqIdentifier', verbose_name='RefSeq identifier'),
        ),
        migrations.AlterField(
            model_name='targetgene',
            name='wt_sequence',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_targets', to='genome.WildTypeSequence', verbose_name='Wild-type Sequence'),
        ),
        migrations.AlterField(
            model_name='wildtypesequence',
            name='sequence',
            field=models.TextField(default=None, validators=[genome.validators.validate_wildtype_sequence], verbose_name='Wild-type sequence'),
        ),
    ]
