# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-16 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0011_auto_20180416_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetgene',
            name='wt_sequence',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_target', to='genome.WildTypeSequence', verbose_name='Wild-type Sequence'),
        ),
    ]
