# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-17 05:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_auto_20180417_1539'),
        ('genome', '0012_auto_20180416_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetgene',
            name='ensembl_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='associated_targets', to='metadata.EnsemblIdentifier'),
        ),
        migrations.AddField(
            model_name='targetgene',
            name='refseq_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='associated_targets', to='metadata.RefseqIdentifier'),
        ),
        migrations.AddField(
            model_name='targetgene',
            name='uniprot_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='associated_targets', to='metadata.UniprotIdentifier'),
        ),
        migrations.AlterField(
            model_name='targetgene',
            name='wt_sequence',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='genome.WildTypeSequence', verbose_name='Wild-type Sequence'),
        ),
    ]
