# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-17 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0013_auto_20180417_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='genome',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='genome.ReferenceGenome', verbose_name='Reference genome'),
        ),
        migrations.AlterField(
            model_name='referencegenome',
            name='ensembl_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_referencegenomes', to='metadata.EnsemblIdentifier', verbose_name='Ensembl identifier'),
        ),
        migrations.AlterField(
            model_name='referencegenome',
            name='refseq_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_referencegenomes', to='metadata.RefseqIdentifier', verbose_name='RefSeq identifier'),
        ),
        migrations.AlterField(
            model_name='targetgene',
            name='ensembl_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='associated_targetgenes', to='metadata.EnsemblIdentifier'),
        ),
        migrations.AlterField(
            model_name='targetgene',
            name='refseq_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='associated_targetgenes', to='metadata.RefseqIdentifier'),
        ),
        migrations.AlterField(
            model_name='targetgene',
            name='uniprot_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='associated_targetgenes', to='metadata.UniprotIdentifier'),
        ),
    ]
