# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2021-01-19 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("GENERAL", "GENERAL"),
                            ("POWERUSER", "POWERUSER"),
                        ],
                        default=manager.models.Role("GENERAL"),
                        max_length=255,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userrole",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]

    def apply(self, project_state, schema_editor, collect_sql=False):
        retval = super().apply(project_state, schema_editor, collect_sql)

        from manager.models import User

        for u in User.objects.all():
            u.save()  # trigger post_save signal to create default userrole

        return retval
